# Generated by Django 4.0.4 on 2022-05-21 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pleir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/')),
                ('Nick', models.CharField(default='Pleir', max_length=50)),
                ('idHash', models.CharField(max_length=256)),
                ('PublicKeuSolana', models.CharField(max_length=50)),
                ('Money', models.FloatField(default=0)),
                ('Distansion', models.FloatField(default=0)),
                ('Record', models.FloatField(default=0)),
                ('DataRegistr', models.DateField()),
                ('DataVixada', models.DateTimeField()),
                ('Energia', models.IntegerField()),
                ('EnergiaMax', models.IntegerField()),
                ('isSiter', models.BooleanField(default=False)),
                ('nonitka', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Сlothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('PhotoNFT', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='NFTs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nick', models.CharField(default='defolt', max_length=20)),
                ('idHash', models.CharField(max_length=256)),
                ('Energia', models.IntegerField()),
                ('EnergiaMax', models.IntegerField()),
                ('DataSozdania', models.DateField()),
                ('DataVixada', models.DateTimeField()),
                ('ClothesTip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CryptoRunner.сlothes')),
                ('Pleir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CryptoRunner.pleir')),
            ],
        ),
        migrations.CreateModel(
            name='MARKETPLACEmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoimost', models.FloatField(default=0.05)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CryptoRunner.nfts')),
            ],
        ),
    ]
