# Generated by Django 4.0.4 on 2022-05-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoRunner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfts',
            name='СlothesTip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CryptoRunner.сlothes'),
        ),
    ]
