# Generated by Django 4.0.4 on 2022-04-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoRunner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfts',
            name='Narameter',
        ),
        migrations.RemoveField(
            model_name='nfts',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='pleir',
            name='Nick',
        ),
        migrations.RemoveField(
            model_name='pleir',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='pleir',
            name='plei',
        ),
    ]
