# Generated by Django 4.0.4 on 2022-05-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoRunner', '0002_alter_nfts_сlothestip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfts',
            old_name='СlothesTip',
            new_name='ClothesTip',
        ),
    ]
