# Generated by Django 4.0.4 on 2022-04-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoRunner', '0002_remove_nfts_narameter_remove_nfts_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pleir',
            name='nonitka',
            field=models.BooleanField(default=True),
        ),
    ]
