# Generated by Django 4.0.4 on 2022-05-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoRunner', '0003_pleir_nonitka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfts',
            name='cap',
        ),
        migrations.RemoveField(
            model_name='nfts',
            name='gloves',
        ),
        migrations.RemoveField(
            model_name='nfts',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='nfts',
            name='suit',
        ),
        migrations.RemoveField(
            model_name='nfts',
            name='trousers',
        ),
    ]
