# Generated by Django 4.0.4 on 2022-05-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoRunner', '0003_rename_сlothestip_nfts_clothestip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacemodel',
            name='idHash',
        ),
    ]
